name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          repository: linuxdeepin/linglong-builder-demo

      - name: Run a one-line script
        run: echo Hello, world!
      - name: Setup ll-builder
        run: |
          echo "deb [trusted=yes] https://ci.deepin.com/repo/obs/linglong:/CI:/release/xUbuntu_24.04/ ./" | sudo tee /etc/apt/sources.list.d/linglong.list
          sudo apt update
          sudo apt-get install -y --no-install-recommends linglong-builder
          ll-builder build
